name: GitHub Classroom Workflow

on:
  push:
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitHub Classroom autograding
        uses: education/autograding@v1
